import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../components/Nav";
import Main from "../components/Main";
import Services from "../components/Services";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Evropa Kombi Prevoz</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      <Main />
      <Services />
    </div>
  );
}
